broadcast-settings:
    always-broadcast: true
    broadcast-legends: true
    broadcast-ultra-beasts: true
    broadcast-shinies: true
default-generator-settings:
    blocked-types:
    - Hoopa
    blocked-specs:
    - hoopa
    allow-legends: true
    allow-ultra-beasts: true
    shiny-chance: 0.05
database-details:
    pool-name: WonderTrade
    ip: 0.0.0.0
    port: 3306
    username: admin
    password: password
    database: WonderTrade
    max-pool-size: 30
admin-u-i:
    gui-settings:
        title: WonderTrade
        height: 6
        fill-type: BLOCK
        filler-items:
            one:
                enabled: true
                type: minecraft:stained_glass_pane
                amount: 1
                damage: 15
                name: ' '
                lore: []
                nbt: {}
    page-positions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    next-page-button:
        x-pos: 8
        y-pos: 5
        enabled: true
        type: pixelmon:trade_holder_right
        amount: 1
        damage: 0
        name: '&aNext Page'
        lore: []
        nbt: {}
    previous-page-button:
        x-pos: 0
        y-pos: 5
        enabled: true
        type: pixelmon:trade_holder_left
        amount: 1
        damage: 0
        name: '&aPrevious Page'
        lore: []
        nbt: {}
    sprites:
        name: '&b%species_name% %nickname%'
        lore:
        - '&7Level: &b%level%'
        - '&7Shiny: &b%shiny%'
        - '&7Gender: %gender%'
        - '&7Breedable: %breedable%'
        - '&7Friendship: %friendship%'
        - '&7Nature: &b%nature%'
        - '&7Form: &b%form%'
        - '&7Growth: &b%size%'
        - '&7Ability: &b%ability%'
        - '&7Friendship: &b%friendship%'
        - '&7Untradeable: &b%untradeable%'
        - '&7Custom Texture: &b%custom_texture%'
        - ' '
        - '&7IVs (&b%iv_percentage%%&7):'
        - '    §7HP: %iv_hp% §d| §7Atk: %iv_attack% §d| §7Def: %iv_defence%'
        - '    §7SAtk: %iv_spattack% §d| §7SDef: %iv_spdefence% §d| §7Spd: %iv_speed%'
        - ' '
        - '&7EVs:'
        - '    §7HP: &b%ev_hp% §d| §7Atk: &b%ev_attack% §d| §7Def: &b%ev_defence%'
        - '    §7SAtk: &b%ev_spattack% §d| §7SDef: &b%ev_spdefence% §d| §7Spd: &b%ev_speed%'
        - ' '
        - '&7Moves:'
        - '    &b%move_1%'
        - '    &b%move_2%'
        - '    &b%move_3%'
        - '    &b%move_4%'
        - ' '
        - '%mew_cloned%'
        - '%trio_gemmed%'
        untrdeable-true-format: '&aTRUE'
        untradeable-false-format: '&cFALSE'
        ability-format: '%ability_name% %ability_ha%'
        ha-format: '&7(&c&lHA&7)'
        male-format: '&bMale'
        female-format: '&dFemale'
        none-format: '&fNONE'
        shiny-true-format: '&aTRUE'
        shiny-false-format: '&cFALSE'
        unbreedable-true-format: '&aTRUE'
        unbreedable-false-format: '&cFALSE'
        mew-cloned-format: '&7Times Cloned: %cloned%'
        gemmed-format: '&7Gemmed: %gemmed%'
        nature-format: '%nature_name% %mint_nature%'
        mint-nature-format: '&7(%mint_nature_name%&7)'
        normal-iv-colour: '&b'
        hyper-iv-colour: '&e'
gui-settings:
    title: WonderTrade
    height: 5
    fill-type: BLOCK
    filler-items:
        one:
            enabled: true
            type: minecraft:stained_glass_pane
            amount: 1
            damage: 15
            name: ' '
            lore: []
            nbt: {}
level-too-low-item:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 14
    name: '&c&lLevel too low'
    lore: []
    nbt: {}
untradeable-item:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 14
    name: '&c&lUntradeable'
    lore: []
    nbt: {}
click-to-confirm-button:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 5
    name: '&a&lClick to confirm'
    lore: []
    nbt: {}
none-selected-item:
    x-pos: 5
    y-pos: 2
    enabled: true
    type: minecraft:barrier
    amount: 1
    damage: 0
    name: '&c&lNone selected'
    lore: []
    nbt: {}
sprite-config:
    name: '&b%species_name% %nickname%'
    lore:
    - '&7Level: &b%level%'
    - '&7Shiny: &b%shiny%'
    - '&7Gender: %gender%'
    - '&7Breedable: %breedable%'
    - '&7Friendship: %friendship%'
    - '&7Nature: &b%nature%'
    - '&7Form: &b%form%'
    - '&7Growth: &b%size%'
    - '&7Ability: &b%ability%'
    - '&7Friendship: &b%friendship%'
    - '&7Untradeable: &b%untradeable%'
    - '&7Custom Texture: &b%custom_texture%'
    - ' '
    - '&7IVs (&b%iv_percentage%%&7):'
    - '    §7HP: %iv_hp% §d| §7Atk: %iv_attack% §d| §7Def: %iv_defence%'
    - '    §7SAtk: %iv_spattack% §d| §7SDef: %iv_spdefence% §d| §7Spd: %iv_speed%'
    - ' '
    - '&7EVs:'
    - '    §7HP: &b%ev_hp% §d| §7Atk: &b%ev_attack% §d| §7Def: &b%ev_defence%'
    - '    §7SAtk: &b%ev_spattack% §d| §7SDef: &b%ev_spdefence% §d| §7Spd: &b%ev_speed%'
    - ' '
    - '&7Moves:'
    - '    &b%move_1%'
    - '    &b%move_2%'
    - '    &b%move_3%'
    - '    &b%move_4%'
    - ' '
    - '%mew_cloned%'
    - '%trio_gemmed%'
    untrdeable-true-format: '&aTRUE'
    untradeable-false-format: '&cFALSE'
    ability-format: '%ability_name% %ability_ha%'
    ha-format: '&7(&c&lHA&7)'
    male-format: '&bMale'
    female-format: '&dFemale'
    none-format: '&fNONE'
    shiny-true-format: '&aTRUE'
    shiny-false-format: '&cFALSE'
    unbreedable-true-format: '&aTRUE'
    unbreedable-false-format: '&cFALSE'
    mew-cloned-format: '&7Times Cloned: %cloned%'
    gemmed-format: '&7Gemmed: %gemmed%'
    nature-format: '%nature_name% %mint_nature%'
    mint-nature-format: '&7(%mint_nature_name%&7)'
    normal-iv-colour: '&b'
    hyper-iv-colour: '&e'
cooldown-seconds: 3600
min-required-level: 30
number-in-pool: 30
selected-sprite-pos: 23
persistent-pool: true
disable-u-i: false
