pokemon-broadcast:
- ' '
- '&e%forge_name%&7 added a &e%is_shiny%%is_ultra_beast%%is_legend%&b%pokemon%&7 to
    the &b&lWonderTrade'
- ' '
shiny-replacement: 'Shiny '
ultra-beast-replacement: 'UltraBeast '
legend-replacement: 'Legend '
trade-successful: '&e&l(!) &eWonderTrade was successful! Check your party to see what
    you got'
cooldown-message: '&c&l(!) &cYou cannot use the WonderTrade yet. You''re still on
    cooldown'
minimum-party-size: '&c&l(!) &cYou must have more than 1 pokemon in your party!'
confirm-sell: '&e&l(!) &ePlease type the command again to confirm you wish to sell
    the slot %slot%'
removed-pokemon: '&e&l(!) &eRemoved pokemon from the WonderTrade pool and replaced
    it with a new random one'
command-error: '&c&l(!) &cIncorrect slot number! /wt <slot>'
